# Generated by Django 2.2.6 on 2019-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='min_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
